name: Build and Upload Ignited
on:
  workflow_dispatch:

jobs:
  build:
    name: Build and upload Ignited
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-latest'
            version: '15.4'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --recursive --init

      - name: Install dependencies
        run: brew install ldid

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with:
          xcode-version: ${{ matrix.version }}

      - name: Build Ignited
        run: |
          xcodebuild -project Ignited.xcodeproj \
          -scheme Ignited \
          -sdk iphoneos \
          archive -archivePath ./archive \
          CODE_SIGNING_REQUIRED=NO \
          AD_HOC_CODE_SIGNING_ALLOWED=YES \
          CODE_SIGNING_ALLOWED=NO \
          DEVELOPMENT_TEAM=AQKFQ7V9C4 \
          ORG_IDENTIFIER=com.litritt \
          | xcpretty && exit ${PIPESTATUS[0]}
      - name: Fakesign app
        run: |
          rm -rf archive.xcarchive/Products/Applications/Ignited.app/Frameworks/DeltraCore.framework/Frameworks/
          ldid -S Ignited/Resources/tempEnt.plist archive.xcarchive/Products/Applications/Ignited.app/Delta
      - name: Convert to IPA
        run: |
          mkdir Payload
          mkdir Payload/Ignited.app
          cp -R archive.xcarchive/Products/Applications/Ignited.app/ Payload/Ignited.app/
          zip -r Ignited.ipa Payload
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Ignited.ipa
          path: Ignited.ipa
